### ISSUE TITLE
build: patch crates for rgb v0.11

### ISSUE THREAD

**Issue by shuimuliang** [RGB-WG/rgb-schemata#23]
Cargo.toml

```toml
[patch.crates-io]
rgb-core = { git = "https://github.com/RGB-WG/rgb-core", branch = "v0.11" }
rgb-invoice = { git = "https://github.com/RGB-WG/rgb-std", branch = "v0.11" }
rgb-std = { git = "https://github.com/RGB-WG/rgb-std", branch = "v0.11" }
```
